CREATE OR ALTER VIEW [dbo].[vwNConformidadeAcoesEmAberto] AS
SELECT
	TACAO_CORRETIVA.COD_N_CONFORMIDADE AS 'Cód. Não Conf.',
	TN_CONFORMIDADE.COD_OS_COMPLETO AS 'OS',
	CONVERT(DATE, TN_CONFORMIDADE.DATA) AS 'Data de Abertura',
	TN_CONFORMIDADE.CLIENTE AS 'Cliente',
	TN_CONFORMIDADE.FASE AS 'Fase',
	TN_CONFORMIDADE.TITULO AS 'Não Conformidade',
	TN_CONFORMIDADE.RESPONSAVEL AS 'Responsável pela Não Conformidade',
	TACAO_CORRETIVA.NOME AS 'Ação',
--	TN_CONFORMIDADE.STATUS_RNC AS 'Status da Não Conformidade',
	CONVERT(DATE, TACAO_CORRETIVA.PRAZO_IMPLEMENTACAO) AS 'Prazo de Implementação',
	TACAO_CORRETIVA.RESPONSAVEL AS 'Responsável pela Ação'
--	TACAO_CORRETIVA.DT_IMPLEMENTACAO AS 'Data de Implementação'
FROM
	TACAO_CORRETIVA
INNER JOIN TN_CONFORMIDADE
	ON TACAO_CORRETIVA.COD_N_CONFORMIDADE = TN_CONFORMIDADE.CODIGO
WHERE
--	TACAO_CORRETIVA.PRAZO_IMPLEMENTACAO IS NOT NULL AND
	TN_CONFORMIDADE.DT_CONCLUSAO IS NULL AND
	TACAO_CORRETIVA.COD_EMPRESA = 1 AND
	TACAO_CORRETIVA.DT_IMPLEMENTACAO IS NULL
GO


